### ISSUE TITLE
Whombat does not work on Python 3.11

### ISSUE THREAD

**Issue by mbsantiago** [mbsantiago/whombat#63]
When installing Whombat using `pip` in Python 3.11:  

```sh
pip install whombat
```  

and then attempting to run it from the command line:  

```sh
whombat
```  

the following error occurs:  

```sh
ImportError: cannot import name 'batched' from 'itertools' (unknown location)
```  

It looks like `batched` was introduced in Python 3.12, so Whombat may be using an incompatible feature in Python 3.11.  

### **Steps to Reproduce**  
1. Install Python 3.11  
2. Run `pip install whombat`  
3. Execute `whombat` in the terminal  

### **Expected Behavior**  
Whombat should run without errors on Python 3.11.  

### **Actual Behavior**  
It fails with an `ImportError` related to `itertools.batched`.  

### **Environment**  
- **Python version:** 3.11  
- **Whombat version:** 0.8.2  
- **OS:** Linux  

### **Acknowledgements**  
Thanks to Peter Prince for pointing out this issue!
